language: python
services:
  - docker

before_install:
  - docker build -t ml_drought .
  - docker run ml_drought /bin/bash -c "source activate esowc-drought; pytest; mypy src"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create -f environment.ubuntu.cpu.yml
  - source activate esowc-drought

script:
  - mypy src
  - pytest

notifications:
  slack:
    rooms:
      - drought-research:6LfQgoVyKQgyamPA8yICbwaJ#ecmwf_summer_of_code
