name: esowc-drought
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - aws-sam-translator=1.11.0
  - aws-xray-sdk=0.95
  - backports=1.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.7.1
  - boto=2.49.0
  - boto3=1.9.153
  - botocore=1.12.153
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cdsapi=0.1.4
  - certifi=2019.3.9
  - cffi=1.12.3
  - cfn-lint=0.20.2
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - cookies=2.2.1
  - cryptography=2.6.1
  - curl=7.62.0
  - dill=0.2.9
  - docker-py=4.0.1
  - docker-pycreds=0.4.0
  - docutils=0.14
  - ecdsa=0.13
  - entrypoints=0.3
  - esmf=7.1.0
  - esmpy=7.1.0
  - flake8=3.7.7
  - flask=1.0.3
  - future=0.17.1
  - gmp=6.1.2
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - itsdangerous=1.1.0
  - jinja2=2.10.1
  - jmespath=0.9.4
  - jpeg=9c
  - jsondiff=1.1.2
  - jsonpatch=1.23
  - jsonpickle=1.1
  - jsonpointer=2.0
  - jsonschema=3.0.0a3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.62.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libssh2=1.8.2
  - libstdcxx-ng=8.2.0
  - libxml2=2.9.9
  - libxslt=1.1.32
  - lxml=4.3.3
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - mock=3.0.5
  - more-itertools=4.3.0
  - moto=1.3.8
  - mpi=1.0
  - mpich=3.2.1
  - multiprocess=0.70.7
  - mypy=0.701
  - mypy_extensions=0.4.1
  - ncurses=6.1
  - netcdf-fortran=4.4.5
  - netcdf4=1.5.1.2
  - numpy=1.16.3
  - openblas=0.3.6
  - openssl=1.1.1b
  - packaging=19.0
  - pandas=0.24.2
  - pathos=0.2.3
  - pip=19.1
  - pluggy=0.11.0
  - pox=0.2.5
  - ppft=1.6.4.9
  - psutil=5.4.8
  - py=1.8.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pycryptodome=3.7.3
  - pyflakes=2.1.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyrsistent=0.15.2
  - pysocks=1.6.8
  - pytest=4.4.2
  - pytest-flake8=1.0.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-jose=2.0.2
  - pytz=2019.1
  - pyyaml=5.1
  - readline=7.0
  - requests=2.21.0
  - responses=0.9.0
  - s3transfer=0.2.0
  - scipy=1.3.0
  - setuptools=41.0.1
  - six=1.12.0
  - soupsieve=1.9.1
  - sqlite=3.28.0
  - tk=8.6.8
  - typed-ast=1.3.5
  - urllib3=1.24.2
  - websocket-client=0.56.0
  - werkzeug=0.15.4
  - wheel=0.33.1
  - wrapt=1.11.1
  - xarray=0.12.1
  - xesmf=0.1.1
  - xmltodict=0.12.0
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
