name: esowc-drought
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cffi=1.12.3
  - cloudpickle=1.2.1
  - cpuonly=1.0
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask-core=2.3.0
  - dbus=1.13.6
  - decorator=4.4.0
  - entrypoints=0.3
  - expat=2.2.5
  - flake8=3.7.8
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=64.2
  - imageio=2.5.0
  - importlib_metadata=0.20
  - intel-openmp=2019.4
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - jedi=0.15.1
  - joblib=0.13.2
  - jpeg=9c
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.8.3
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mccabe=0.6.1
  - mkl=2019.4
  - more-itertools=7.2.0
  - mypy=0.720
  - mypy_extensions=0.4.1
  - ncurses=6.1
  - networkx=2.3
  - ninja=1.9.0
  - numpy=1.17.1
  - olefile=0.46
  - openssl=1.1.1c
  - packaging=19.0
  - pandas=0.25.1
  - parso=0.5.1
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.2.3
  - pluggy=0.12.0
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pygments=2.4.2
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pytest=5.0.1
  - pytest-flake8=1.0.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytz=2019.2
  - pywavelets=1.0.3
  - qt=5.9.7
  - readline=8.0
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - setuptools=41.2.0
  - shap=0.30.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.9
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.35.0
  - traitlets=4.3.2
  - typed-ast=1.4.0
  - typing_extensions=3.7.4
  - wcwidth=0.1.7
  - wheel=0.33.6
  - xarray=0.12.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.0
